-- Marketing OS · Kitachi — dữ liệu khởi tạo
-- Chạy SAU schema.sql

insert into members (name, short_name, role, dept, manager, email, pin, kind, desk, sort_order) values
('Công Tuân','Tuân','Leader Team','Quản lý',NULL,'tuan@kitachi.vn','1111','leader','leader',NULL),
('Trang Linh','Linh','Content Marketing (chung)','Nội dung','Công Tuân','linh@kitachi.vn','2222','writer','social',NULL),
('Hồng Hạnh','Hạnh','Content Marketing TikTok','Nội dung','Trang Linh','hanh@kitachi.vn','3333','writer','tiktok',NULL),
('Phạm Vỹ','Vỹ','Designer','Thiết kế','Công Tuân','vy@kitachi.vn','4444','design','design',NULL),
('Diệu Thảo','Thảo','Editor','Thiết kế','Phạm Vỹ','thao@kitachi.vn','5555','design','edit',NULL);

insert into channels (id, name, platform, followers, role, style, priority, target_week, note, stream, owner_content, owner_design, budget_month, spent_month, aud_age, aud_gender, aud_loc, aud_hour, growth) values
(1,'@micaykitachi','TikTok',5200,'Kênh thương hiệu CHÍNH','Món ăn bắt mắt, review, trend, khuyến mãi, không khí quán. Nhịp nhanh, bắt trend.','CAO',5,'Đăng đều, giữ nhịp','tiktok','Hồng Hạnh','Diệu Thảo',8000000,2800000,'{"18-24": 36.1, "25-34": 43.3, "35-44": 11.3, "45-54": 7.2, "≥55": 2.1}'::jsonb,'{"Nam": 44, "Nữ": 56}'::jsonb,'[{"n": "Quảng Ngãi", "v": 52}, {"n": "Quảng Nam", "v": 12}, {"n": "Đà Nẵng", "v": 11}, {"n": "TP Hồ Chí Minh", "v": 8}, {"n": "Bình Định", "v": 6}]'::jsonb,'[{"h": "06-09", "v": 6}, {"h": "09-12", "v": 13}, {"h": "12-14", "v": 13}, {"h": "14-18", "v": 10}, {"h": "18-21", "v": 31}, {"h": "21-24", "v": 20}]'::jsonb,'[4253, 4502, 4694, 4803, 4991, 5254]'::jsonb),
(2,'@chuyenmicaykitachi','TikTok',1000,'Series hậu trường / quy trình – tạo niềm tin','Kể chuyện, phong cách tài liệu: sơ chế, nhập nguyên liệu, bếp trung tâm. Thumbnail tiêu đề lớn + dấu “?” vàng, tag SERIES.','CAO',3,'Bản sắc riêng – không trộn tông với kênh chính','tiktok','Hồng Hạnh','Diệu Thảo',4000000,1400000,'{"18-24": 38.0, "25-34": 47.8, "35-44": 12.0, "45-54": 2.2, "≥55": 0.0}'::jsonb,'{"Nam": 44, "Nữ": 56}'::jsonb,'[{"n": "Quảng Ngãi", "v": 52}, {"n": "Quảng Nam", "v": 12}, {"n": "Đà Nẵng", "v": 11}, {"n": "TP Hồ Chí Minh", "v": 8}, {"n": "Bình Định", "v": 6}]'::jsonb,'[{"h": "06-09", "v": 9}, {"h": "09-12", "v": 13}, {"h": "12-14", "v": 16}, {"h": "14-18", "v": 13}, {"h": "18-21", "v": 34}, {"h": "21-24", "v": 17}]'::jsonb,'[855, 827, 867, 890, 1022, 1011]'::jsonb),
(3,'@bobistro76','TikTok',224,'Thương hiệu Bò Bistro (bò nướng & lẩu)','Món nướng / lẩu tông điện ảnh, ấm, cận cảnh thịt. Đề cao cảm giác ngon & sang.','RẤT CAO',5,'Cần bứt tốc – ưu tiên nguồn lực dựng','tiktok','Hồng Hạnh','Diệu Thảo',10000000,3500000,'{"18-24": 39.4, "25-34": 42.6, "35-44": 12.8, "45-54": 3.2, "≥55": 2.1}'::jsonb,'{"Nam": 44, "Nữ": 56}'::jsonb,'[{"n": "Quảng Ngãi", "v": 52}, {"n": "Quảng Nam", "v": 12}, {"n": "Đà Nẵng", "v": 11}, {"n": "TP Hồ Chí Minh", "v": 8}, {"n": "Bình Định", "v": 6}]'::jsonb,'[{"h": "06-09", "v": 7}, {"h": "09-12", "v": 12}, {"h": "12-14", "v": 14}, {"h": "14-18", "v": 10}, {"h": "18-21", "v": 36}, {"h": "21-24", "v": 17}]'::jsonb,'[197, 226, 244, 238, 183, 190]'::jsonb),
(4,'@anuongquangngai','TikTok',21300,'Kênh review / dẫn dắt – kéo khám phá','Review quán ăn POV chân thực, tiêu đề nổi bật, giọng gần gũi địa phương.','CAO',4,'Kênh mạnh nhất – dùng để kéo traffic về các kênh khác','tiktok','Hồng Hạnh','Diệu Thảo',5000000,1750000,'{"18-24": 42.7, "25-34": 41.7, "35-44": 13.5, "45-54": 2.1, "≥55": 0.0}'::jsonb,'{"Nam": 44, "Nữ": 56}'::jsonb,'[{"n": "Quảng Ngãi", "v": 52}, {"n": "Quảng Nam", "v": 12}, {"n": "Đà Nẵng", "v": 11}, {"n": "TP Hồ Chí Minh", "v": 8}, {"n": "Bình Định", "v": 6}]'::jsonb,'[{"h": "06-09", "v": 6}, {"h": "09-12", "v": 14}, {"h": "12-14", "v": 19}, {"h": "14-18", "v": 12}, {"h": "18-21", "v": 31}, {"h": "21-24", "v": 16}]'::jsonb,'[17520, 18260, 19016, 19809, 20520, 21286]'::jsonb),
(5,'@lacaquangngai','TikTok',0,'Kênh hệ thống (review / địa phương)','Nội dung ẩm thực – địa phương Quảng Ngãi; đồng bộ giọng review.','TRUNG BÌNH',2,'Cập nhật số follow khi có','tiktok','Hồng Hạnh','Diệu Thảo',2000000,700000,'{"18-24": 40.2, "25-34": 41.2, "35-44": 15.7, "45-54": 2.9, "≥55": 0.0}'::jsonb,'{"Nam": 44, "Nữ": 56}'::jsonb,'[{"n": "Quảng Ngãi", "v": 52}, {"n": "Quảng Nam", "v": 12}, {"n": "Đà Nẵng", "v": 11}, {"n": "TP Hồ Chí Minh", "v": 8}, {"n": "Bình Định", "v": 6}]'::jsonb,'[{"h": "06-09", "v": 7}, {"h": "09-12", "v": 13}, {"h": "12-14", "v": 19}, {"h": "14-18", "v": 10}, {"h": "18-21", "v": 34}, {"h": "21-24", "v": 16}]'::jsonb,'[0, 3, 0, 2, 33, 10]'::jsonb),
(6,'Fanpage Mì Cay Kitachi','Facebook',0,'Fanpage thương hiệu chính','Thông báo ưu đãi, hình ảnh món, tương tác với khách quen. Tông thân thiện, gần gũi.','CAO',4,NULL,'social','Trang Linh','Phạm Vỹ',12000000,4200000,'{"18-24": 17.0, "25-34": 39.6, "35-44": 26.4, "45-54": 13.2, "≥55": 3.8}'::jsonb,'{"Nam": 41, "Nữ": 59}'::jsonb,'[{"n": "Quảng Ngãi", "v": 61}, {"n": "Quảng Nam", "v": 10}, {"n": "Đà Nẵng", "v": 9}, {"n": "TP Hồ Chí Minh", "v": 7}, {"n": "Bình Định", "v": 5}]'::jsonb,'[{"h": "06-09", "v": 6}, {"h": "09-12", "v": 13}, {"h": "12-14", "v": 13}, {"h": "14-18", "v": 15}, {"h": "18-21", "v": 37}, {"h": "21-24", "v": 18}]'::jsonb,'[0, 31, 39, 29, 46, 0]'::jsonb),
(7,'Instagram Mì Cay Kitachi','Instagram',0,'Kênh hình ảnh – thẩm mỹ món','Ảnh / infographic tông sáng, bố cục gọn, ưu tiên lượt lưu.','TRUNG BÌNH',2,NULL,'social','Trang Linh','Phạm Vỹ',3000000,1050000,'{"18-24": 45.2, "25-34": 38.7, "35-44": 10.8, "45-54": 1.1, "≥55": 4.3}'::jsonb,'{"Nam": 35, "Nữ": 65}'::jsonb,'[{"n": "Quảng Ngãi", "v": 48}, {"n": "Đà Nẵng", "v": 16}, {"n": "TP Hồ Chí Minh", "v": 13}, {"n": "Quảng Nam", "v": 9}, {"n": "Hà Nội", "v": 4}]'::jsonb,'[{"h": "06-09", "v": 9}, {"h": "09-12", "v": 10}, {"h": "12-14", "v": 18}, {"h": "14-18", "v": 9}, {"h": "18-21", "v": 36}, {"h": "21-24", "v": 19}]'::jsonb,'[0, 0, 43, 0, 0, 18]'::jsonb),
(8,'Website hệ thống','Website',0,'Kênh SEO – kéo tìm kiếm','Bài chuẩn SEO, giọng trung tính, luôn kèm ảnh thật của quán.','TRUNG BÌNH',1,NULL,'social','Trang Linh','Phạm Vỹ',2000000,700000,'{"18-24": 13.0, "25-34": 39.0, "35-44": 28.0, "45-54": 14.0, "≥55": 6.0}'::jsonb,'{"Nam": 47, "Nữ": 53}'::jsonb,'[{"n": "Quảng Ngãi", "v": 66}, {"n": "Quảng Nam", "v": 9}, {"n": "Đà Nẵng", "v": 8}, {"n": "TP Hồ Chí Minh", "v": 6}, {"n": "Khác", "v": 11}]'::jsonb,'[{"h": "06-09", "v": 11}, {"h": "09-12", "v": 8}, {"h": "12-14", "v": 17}, {"h": "14-18", "v": 14}, {"h": "18-21", "v": 31}, {"h": "21-24", "v": 18}]'::jsonb,'[0, 41, 0, 0, 0, 2]'::jsonb),
(9,'Google Maps – cơ sở 1','Google Maps',0,'Kênh tại chỗ – kéo khách ở gần','Ảnh thật, cập nhật giờ mở cửa và khuyến mãi ngắn.','CAO',1,'Mỗi cơ sở nên tách thành 1 dòng riêng','social','Trang Linh','Phạm Vỹ',4000000,1400000,'{"18-24": 9.9, "25-34": 35.6, "35-44": 33.7, "45-54": 13.9, "≥55": 6.9}'::jsonb,'{"Nam": 49, "Nữ": 51}'::jsonb,'[{"n": "Quảng Ngãi", "v": 74}, {"n": "Quảng Nam", "v": 8}, {"n": "Đà Nẵng", "v": 7}, {"n": "Bình Định", "v": 4}, {"n": "Khác", "v": 7}]'::jsonb,'[{"h": "06-09", "v": 5}, {"h": "09-12", "v": 11}, {"h": "12-14", "v": 17}, {"h": "14-18", "v": 15}, {"h": "18-21", "v": 35}, {"h": "21-24", "v": 18}]'::jsonb,'[7, 38, 22, 41, 35, 0]'::jsonb),
(10,'YouTube hệ thống','YouTube',0,'Kênh video dài – lưu trữ thương hiệu','Video 5–10 phút, dựng chỉn chu, có intro và outro CTA.','THẤP',1,NULL,'social','Trang Linh','Phạm Vỹ',1000000,350000,'{"18-24": 30.7, "25-34": 33.7, "35-44": 21.8, "45-54": 6.9, "≥55": 6.9}'::jsonb,'{"Nam": 52, "Nữ": 48}'::jsonb,'[{"n": "Quảng Ngãi", "v": 44}, {"n": "TP Hồ Chí Minh", "v": 15}, {"n": "Đà Nẵng", "v": 12}, {"n": "Hà Nội", "v": 9}, {"n": "Khác", "v": 20}]'::jsonb,'[{"h": "06-09", "v": 10}, {"h": "09-12", "v": 12}, {"h": "12-14", "v": 18}, {"h": "14-18", "v": 12}, {"h": "18-21", "v": 37}, {"h": "21-24", "v": 22}]'::jsonb,'[0, 0, 22, 57, 60, 20]'::jsonb),
(11,'ShopeeFood – cơ sở 1','Shopee',0,'Gian hàng giao đồ ăn, đẩy đơn giờ thấp điểm',NULL,'CAO',2,NULL,'social','Trang Linh','Phạm Vỹ',4000000,0,'{"18-24": 23.1, "25-34": 46.2, "35-44": 23.1, "45-54": 5.5, "≥55": 2.2}'::jsonb,'{"Nam": 38, "Nữ": 62}'::jsonb,'[{"n": "Quảng Ngãi", "v": 71}, {"n": "Quảng Nam", "v": 10}, {"n": "Đà Nẵng", "v": 9}, {"n": "Khác", "v": 10}]'::jsonb,'[{"h": "06-09", "v": 9}, {"h": "09-12", "v": 10}, {"h": "12-14", "v": 16}, {"h": "14-18", "v": 10}, {"h": "18-21", "v": 31}, {"h": "21-24", "v": 17}]'::jsonb,'[0, 32, 38, 0, 38, 0]'::jsonb),
(12,'Zalo OA Kitachi','Zalo',0,'Chăm sóc khách cũ, gửi ưu đãi ZNS',NULL,'TRUNG BÌNH',1,NULL,'social','Trang Linh','Phạm Vỹ',3000000,0,'{"18-24": 17.9, "25-34": 34.0, "35-44": 29.2, "45-54": 15.1, "≥55": 3.8}'::jsonb,'{"Nam": 45, "Nữ": 55}'::jsonb,'[{"n": "Quảng Ngãi", "v": 82}, {"n": "Quảng Nam", "v": 7}, {"n": "Đà Nẵng", "v": 5}, {"n": "Khác", "v": 6}]'::jsonb,'[{"h": "06-09", "v": 10}, {"h": "09-12", "v": 9}, {"h": "12-14", "v": 17}, {"h": "14-18", "v": 12}, {"h": "18-21", "v": 35}, {"h": "21-24", "v": 21}]'::jsonb,'[25, 27, 50, 24, 11, 0]'::jsonb);

insert into projects (id, code, name, status, owner, start, due, progress, budget, spent, color, note) values
(1,'CS2','Khai trương cơ sở 2 — 443 Phan Đình Phùng','Đang chạy','Công Tuân','2026-08-01','2026-10-10',0,189596000,0,'#6D4AFF','Cơ sở 2 cách cơ sở 1 khoảng 670 m trên cùng đường Phan Đình Phùng.'),
(2,'NOIDUNG','Vận hành nội dung thường xuyên','Đang chạy','Trang Linh','2026-08-01','2026-12-31',0,60000000,0,'#0E7490','Guồng sản xuất nội dung 10 kênh, chạy liên tục theo tuần.'),
(3,'TET27','Chiến dịch Tết 2027','Sắp bắt đầu','Công Tuân','2026-11-15','2027-02-10',0,120000000,0,'#D03535','Lên kế hoạch từ tháng 11, chạy cao điểm tháng 1.');

insert into sprints (id, name, start, "end", status, goal) values
(1,'Đợt 1','2026-08-03','2026-08-16','Đang chạy',NULL),
(2,'Đợt 2','2026-08-17','2026-08-30','Sắp tới',NULL),
(3,'Đợt 3','2026-08-31','2026-09-13','Sắp tới','Đẩy mạnh nội dung teaser khai trương'),
(4,'Đợt 4','2026-09-14','2026-09-27','Sắp tới','Hoàn tất toàn bộ ấn phẩm in cho cơ sở 2'),
(5,'Đợt 5','2026-09-28','2026-10-11','Sắp tới',NULL),
(6,'Đợt 6','2026-10-12','2026-10-25','Sắp tới',NULL);

insert into budget (id, project_id, channel_id, cat, name, plan, spent, owner) values
(1,1,NULL,'Quảng cáo','Meta Ads — chiến dịch khai trương',33000000,12400000,'Công Tuân'),
(2,1,NULL,'KOC/KOL','Booking 34 suất KOC & KOL',37600000,8500000,'Công Tuân'),
(3,1,NULL,'In ấn','POSM, standee, menu, tờ rơi',28000000,19200000,'Phạm Vỹ'),
(4,1,NULL,'Sự kiện','Khai trương: sân khấu, MC, lân sư rồng',24600000,0,'Công Tuân'),
(5,1,NULL,'Sản xuất','Chụp ảnh, quay dựng video',22500000,6000000,'Diệu Thảo'),
(6,1,NULL,'Quà tặng','Quà check-in, trợ giá khuyến mãi',29000000,0,'Công Tuân'),
(7,1,NULL,'Dự phòng','Chi phí phát sinh',14896000,0,'Công Tuân'),
(8,2,NULL,'Quảng cáo','Ngân sách duy trì hằng tháng',36000000,9000000,'Trang Linh'),
(9,2,NULL,'Sản xuất','Đạo cụ, thuê thiết bị quay',14000000,3200000,'Hồng Hạnh'),
(10,2,NULL,'Công cụ','Canva Pro, CapCut Pro, kho ảnh',10000000,4100000,'Phạm Vỹ'),
(11,3,NULL,'Quảng cáo','Ngân sách chiến dịch Tết',70000000,0,'Công Tuân'),
(12,3,NULL,'Sản xuất','TVC Tết, bộ ảnh Tết',50000000,0,'Phạm Vỹ'),
(13,2,1,'Quảng cáo kênh','Ngân sách tháng — @micaykitachi',8000000,2800000,'Hồng Hạnh'),
(14,2,2,'Quảng cáo kênh','Ngân sách tháng — @chuyenmicaykitachi',4000000,1400000,'Hồng Hạnh'),
(15,2,3,'Quảng cáo kênh','Ngân sách tháng — @bobistro76',10000000,3500000,'Hồng Hạnh'),
(16,2,4,'Quảng cáo kênh','Ngân sách tháng — @anuongquangngai',5000000,1750000,'Hồng Hạnh'),
(17,2,5,'Quảng cáo kênh','Ngân sách tháng — @lacaquangngai',2000000,700000,'Hồng Hạnh'),
(18,2,6,'Quảng cáo kênh','Ngân sách tháng — Fanpage Mì Cay Kitachi',12000000,4200000,'Trang Linh'),
(19,2,7,'Quảng cáo kênh','Ngân sách tháng — Instagram Mì Cay Kitachi',3000000,1050000,'Trang Linh'),
(20,2,8,'Quảng cáo kênh','Ngân sách tháng — Website hệ thống',2000000,700000,'Trang Linh'),
(21,2,9,'Quảng cáo kênh','Ngân sách tháng — Google Maps – cơ sở 1',4000000,1400000,'Trang Linh'),
(22,2,10,'Quảng cáo kênh','Ngân sách tháng — YouTube hệ thống',1000000,350000,'Trang Linh'),
(23,2,11,'Quảng cáo kênh','Ngân sách tháng — ShopeeFood – cơ sở 1',4000000,0,'Trang Linh'),
(24,2,12,'Quảng cáo kênh','Ngân sách tháng — Zalo OA Kitachi',3000000,0,'Trang Linh');

insert into ads (id, name, platform, channel, goal, status, owner, project_id, budget_id, start, "end", budget, spent, impressions, clicks, conversions, revenue) values
(1,'Khai trương CS2 — Nhận biết','Meta Ads','Fanpage Mì Cay Kitachi','Nhận biết','Đang chạy','Công Tuân',1,1,'2026-07-28','2026-08-25',12000000,4820000,486000,9200,182,0),
(2,'Khai trương CS2 — Tin nhắn','Meta Ads','Fanpage Mì Cay Kitachi','Tin nhắn','Đang chạy','Công Tuân',1,1,'2026-08-01','2026-08-29',9000000,3150000,214000,5400,143,0),
(3,'TikTok Ads — Video view CS2','TikTok Ads','@micaykitachi','Nhận biết','Đang chạy','Công Tuân',1,1,'2026-07-30','2026-08-27',8000000,2900000,612000,14300,96,0),
(4,'Google Maps — Tìm kiếm địa phương','Google Ads','Google Maps – cơ sở 1','Kéo về quán','Đang chạy','Công Tuân',1,1,'2026-08-03','2026-09-02',6000000,1740000,58000,3100,210,0),
(5,'ShopeeFood — Đẩy gian hàng CS2','Nội sàn','ShopeeFood – cơ sở 1','Bán hàng','Đang chạy','Công Tuân',1,1,'2026-08-05','2026-09-04',4000000,1180000,42000,2650,167,8900000),
(6,'Fanpage — Tương tác thường xuyên','Meta Ads','Fanpage Mì Cay Kitachi','Tương tác','Đã kết thúc','Trang Linh',2,8,'2026-07-12','2026-08-11',6000000,5240000,318000,7400,0,0),
(7,'TikTok — Đẩy kênh Bò Bistro','TikTok Ads','@micaykitachi','Tăng follow','Đang chạy','Hồng Hạnh',2,8,'2026-07-21','2026-08-20',5000000,3600000,748000,21400,0,0),
(8,'ZNS — Nhắc khách quay lại','Zalo ZNS','Zalo OA Kitachi','Giữ chân','Đã kết thúc','Trang Linh',2,8,'2026-07-17','2026-08-07',3000000,2850000,9500,1420,118,6200000),
(9,'Chiến dịch Tết — Giai đoạn thử','Meta Ads','Fanpage Mì Cay Kitachi','Nhận biết','Tạm dừng','Công Tuân',3,11,'2026-08-08','2026-09-10',15000000,0,0,0,0,0);

insert into tasks (project_id, sprint_id, code, area, name, detail, owner, assigner, reporter, priority, est, due, status) values
(1,1,'CV-01','Kế hoạch chung','Phân vùng theo HƯỚNG, không theo bán kính',NULL,'Công Tuân',NULL,'Công Tuân','Cao',2,'2026-09-15','Chưa bắt đầu'),
(1,2,'CV-02','Kế hoạch chung','Chốt lý do tồn tại của CN2 (BẮT BUỘC làm trước mọi việc khác)',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',4,'2026-09-15','Chưa bắt đầu'),
(1,3,'CV-03','Kế hoạch chung','Dự báo mức ăn thịt lẫn nhau & đặt ngưỡng cảnh báo',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',8,'2026-09-16','Chưa bắt đầu'),
(1,4,'CV-04','Kế hoạch chung','Chốt chính sách CTKM tránh giẫm chân',NULL,'Công Tuân',NULL,'Công Tuân','Cao',16,'2026-09-16','Chưa bắt đầu'),
(1,5,'CV-05','Kế hoạch chung','Kiểm kê tài sản dùng lại từ chi nhánh 1',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',2,'2026-09-17','Chưa bắt đầu'),
(1,6,'CV-06','Kế hoạch chung','Chốt KPI riêng cho CN2 và KPI hợp nhất 2 chi nhánh',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',4,'2026-09-17','Chưa bắt đầu'),
(1,1,'CV-07','Kế hoạch chung','Lập ngân sách rút gọn & trình duyệt',NULL,'Công Tuân',NULL,'Công Tuân','Cao',8,'2026-09-18','Chưa bắt đầu'),
(1,2,'CV-08','Kế hoạch chung','Chỉnh sửa & đặt in bộ POSM',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',16,'2026-09-20','Chưa bắt đầu'),
(1,3,'CV-09','Kế hoạch chung','Đặt sản xuất biển hiệu, decal mặt tiền',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',2,'2026-09-20','Chưa bắt đầu'),
(1,4,'CV-10','Kế hoạch chung','Chụp bổ sung ảnh không gian chi nhánh 2',NULL,'Trang Linh',NULL,'Công Tuân','Cao',4,'2026-09-24','Chưa bắt đầu'),
(1,5,'CV-11','Kế hoạch chung','Tạo Google Business Profile riêng cho CN2 - RỦI RO CAO',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',8,'2026-09-20','Chưa bắt đầu'),
(1,6,'CV-12','Kế hoạch chung','Giám sát hồ sơ Google CN1 hằng tuần trong 1 tháng',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',16,'2026-09-28','Chưa bắt đầu'),
(1,1,'CV-13','Kế hoạch chung','Đăng ký app giao hàng & chia lại bán kính giao của cả 2 chi nhánh',NULL,'Công Tuân',NULL,'Công Tuân','Cao',2,'2026-09-15','Chưa bắt đầu'),
(1,2,'CV-14','Kế hoạch chung','Cập nhật fanpage, website, Zalo OA',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',4,'2026-09-26','Chưa bắt đầu'),
(1,3,'CV-15','Kế hoạch chung','Cấu hình POS: mã CTKM và mã voucher riêng cho CN2','Phối hợp cùng: IT/POS','Công Tuân',NULL,'Công Tuân','Cao',8,'2026-09-30','Chưa bắt đầu'),
(1,4,'CV-16','Kế hoạch chung','Đặt hạng mục sự kiện khai trương (gọn)',NULL,'Công Tuân',NULL,'Công Tuân','Cao',16,'2026-09-22','Chưa bắt đầu'),
(1,5,'CV-17','Kế hoạch chung','Đào tạo nhân viên CN2 - trọng tâm TỐC ĐỘ PHỤC VỤ',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',2,'2026-10-04','Chưa bắt đầu'),
(1,6,'CV-18','Kế hoạch chung','Thông báo tại chính chi nhánh 1',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',4,'2026-09-28','Chưa bắt đầu'),
(1,1,'CV-19','Kế hoạch chung','Đăng bài công bố & đếm ngược',NULL,'Trang Linh',NULL,'Công Tuân','Cao',8,'2026-09-28','Chưa bắt đầu'),
(1,2,'CV-20','Kế hoạch chung','Chạy quảng cáo LỆCH VỀ PHÍA NAM, không loại trừ được theo bán kính',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',16,'2026-09-28','Chưa bắt đầu'),
(1,3,'CV-21','Kế hoạch chung','Gửi ZNS/SMS cho khách CN1 ở phía Nam thành phố',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',2,'2026-10-03','Chưa bắt đầu'),
(1,4,'CV-22','Kế hoạch chung','Phát tờ rơi CHỈ về hướng Nam từ số 443 trở xuống','Phối hợp cùng: PG','Công Tuân',NULL,'Công Tuân','Cao',4,'2026-09-30','Chưa bắt đầu'),
(1,5,'CV-23','Kế hoạch chung','Booking KOC địa phương (chọn lọc)',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',8,'2026-09-28','Chưa bắt đầu'),
(1,6,'CV-24','Kế hoạch chung','Seeding hội nhóm địa phương','Phối hợp cùng: CTV','Trang Linh',NULL,'Công Tuân','Thấp',16,'2026-09-30','Chưa bắt đầu'),
(1,1,'CV-25','Kế hoạch chung','Tổng duyệt POSM tại điểm bán & xác nhận nhà cung cấp',NULL,'Công Tuân',NULL,'Công Tuân','Cao',2,'2026-10-07','Chưa bắt đầu'),
(1,2,'CV-26','Kế hoạch chung','Chạy đơn test trên app giao hàng & rà tồn kho với bếp','Phối hợp cùng: Vận hành','Công Tuân',NULL,'Công Tuân','Trung bình',4,'2026-10-07','Chưa bắt đầu'),
(1,3,'CV-27','Kế hoạch chung','Setup sớm & chụp ảnh trước giờ mở cửa',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',8,'2026-10-10','Chưa bắt đầu'),
(1,4,'CV-28','Kế hoạch chung','Điều phối sự kiện theo kịch bản',NULL,'Công Tuân',NULL,'Công Tuân','Cao',16,'2026-10-10','Chưa bắt đầu'),
(1,5,'CV-29','Kế hoạch chung','Livestream & đăng story realtime',NULL,'Trang Linh',NULL,'Công Tuân','Cao',2,'2026-10-10','Chưa bắt đầu'),
(1,6,'CV-30','Kế hoạch chung','Check-in nhận quà & thu data khách hàng','Phối hợp cùng: PG','Công Tuân',NULL,'Công Tuân','Thấp',4,'2026-10-10','Chưa bắt đầu'),
(1,1,'CV-31','Kế hoạch chung','Trực fanpage - inbox - bình luận cả ngày',NULL,'Trang Linh',NULL,'Công Tuân','Cao',8,'2026-10-10','Chưa bắt đầu'),
(1,2,'CV-32','Kế hoạch chung','Ghi số liệu CN2 VÀ theo dõi doanh thu CN1 cùng ngày','Phối hợp cùng: Thu ngân','Công Tuân',NULL,'Công Tuân','Trung bình',16,'2026-10-10','Chưa bắt đầu'),
(1,3,'CV-33','Kế hoạch chung','Đăng album cảm ơn & tổng hợp UGC',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',2,'2026-10-11','Chưa bắt đầu'),
(1,4,'CV-34','Kế hoạch chung','Chuyển quảng cáo sang mục tiêu chuyển đổi & retarget',NULL,'Công Tuân',NULL,'Công Tuân','Cao',4,'2026-10-12','Chưa bắt đầu'),
(1,5,'CV-35','Kế hoạch chung','Quản trị đánh giá Google & app cho CẢ 2 chi nhánh',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',8,'2026-10-11','Chưa bắt đầu'),
(1,6,'CV-36','Kế hoạch chung','Gửi voucher lần 2 cho khách đã đến CN2',NULL,'Công Tuân',NULL,'Công Tuân','Cao',16,'2026-10-20','Chưa bắt đầu'),
(1,1,'CV-37','Kế hoạch chung','Báo cáo tuần: CN2 + biến động CN1 + tổng hợp nhất',NULL,'Công Tuân',NULL,'Công Tuân','Cao',2,'2026-10-17','Chưa bắt đầu'),
(1,2,'CV-38','Kế hoạch chung','Điều chỉnh phân vùng & bán kính giao hàng theo dữ liệu thực',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',4,'2026-11-07','Chưa bắt đầu'),
(1,3,'CV-39','Kế hoạch chung','Cập nhật playbook mở chi nhánh trong cùng tỉnh',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',8,'2026-11-09','Chưa bắt đầu'),
(1,4,'TT-01','Content','Quảng Ngãi sắp có thêm một chỗ ăn mì cay nữa...',NULL,'Trang Linh',NULL,'Công Tuân','Cao',16,'2026-09-26','Lên ý tưởng'),
(1,5,'TT-02','Content','Kitachi mở cơ sở 2 - 443 Phan Đình Phùng',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',2,'2026-09-28','Lên ý tưởng'),
(1,6,'TT-03','Content','Hai quán cách nhau có 600 mét, mở làm gì?',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',4,'2026-09-29','Lên ý tưởng'),
(1,1,'TT-04','Content','Chọn cấp độ mấy cho vừa? Xem clip này trước khi gọi',NULL,'Trang Linh',NULL,'Công Tuân','Cao',8,'2026-09-30','Lên ý tưởng'),
(1,2,'TT-05','Content','Âm thanh chữa lành của người mê cay',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',16,'2026-10-01','Lên ý tưởng'),
(1,3,'TT-06','Content','3 ngày trước khi mở quán trông như thế nào',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',2,'2026-10-02','Lên ý tưởng'),
(1,4,'TT-07','Content','Ưu đãi khai trương cơ sở 2 - chỉ áp dụng tại 443',NULL,'Trang Linh',NULL,'Công Tuân','Cao',4,'2026-10-03','Lên ý tưởng'),
(1,5,'TT-08','Content','Dẫn bạn đi một vòng cơ sở mới',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',8,'2026-10-04','Lên ý tưởng'),
(1,6,'TT-09','Content','Ai dám thử cấp độ 7 ngày khai trương?',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',16,'2026-10-05','Lên ý tưởng'),
(1,1,'TT-10','Content','KOC địa phương review cơ sở 2',NULL,'Trang Linh',NULL,'Công Tuân','Cao',2,'2026-10-06','Lên ý tưởng'),
(1,2,'TT-11','Content','Còn 3 ngày - chỉ đường tới 443 Phan Đình Phùng',NULL,'Trang Linh',NULL,'Công Tuân','Cao',4,'2026-10-07','Lên ý tưởng'),
(1,3,'TT-12','Content','Mai khai trương rồi - tổng hợp mọi thứ cần biết',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',8,'2026-10-09','Lên ý tưởng'),
(1,4,'TT-13','Content','Livestream lễ khai trương',NULL,'Trang Linh',NULL,'Công Tuân','Cao',16,'2026-10-10','Lên ý tưởng'),
(1,5,'TT-14','Content','Ngày khai trương ở 443 Phan Đình Phùng',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',2,'2026-10-10','Lên ý tưởng'),
(1,6,'TT-15','Content','Khách nói gì về cơ sở mới',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',4,'2026-10-12','Lên ý tưởng'),
(1,1,'TT-16','Content','5 topping nên gọi thêm khi ăn mì cay',NULL,'Trang Linh',NULL,'Công Tuân','Cao',8,'2026-10-15','Lên ý tưởng'),
(1,2,'TT-17','Content','Dưới 100k ăn được gì ở Kitachi',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',16,'2026-10-19','Lên ý tưởng'),
(1,3,'TT-18','Content','Đi 4 người ăn mì cay hết bao nhiêu?',NULL,'Trang Linh',NULL,'Công Tuân','Cao',2,'2026-10-24','Lên ý tưởng'),
(1,4,'TT-19','Content','Quảng Ngãi sắp có thêm một chỗ ăn mì cay nữa...',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',4,'2026-09-26','Chưa dựng'),
(1,5,'TT-20','Content','Kitachi mở cơ sở 2 - 443 Phan Đình Phùng',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',8,'2026-09-28','Chưa dựng'),
(1,6,'TT-21','Content','Hai quán cách nhau có 600 mét, mở làm gì?',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',16,'2026-09-29','Chưa dựng'),
(1,1,'TT-22','Content','Chọn cấp độ mấy cho vừa? Xem clip này trước khi gọi',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',2,'2026-09-30','Chưa dựng'),
(1,2,'TT-23','Content','Âm thanh chữa lành của người mê cay',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',4,'2026-10-01','Chưa dựng'),
(1,3,'TT-24','Content','3 ngày trước khi mở quán trông như thế nào',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',8,'2026-10-02','Chưa dựng'),
(1,4,'TT-25','Content','Ưu đãi khai trương cơ sở 2 - chỉ áp dụng tại 443',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',16,'2026-10-03','Chưa dựng'),
(1,5,'TT-26','Content','Dẫn bạn đi một vòng cơ sở mới',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',2,'2026-10-04','Chưa dựng'),
(1,6,'TT-27','Content','Ai dám thử cấp độ 7 ngày khai trương?',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',4,'2026-10-05','Chưa dựng'),
(1,1,'TT-28','Content','KOC địa phương review cơ sở 2',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',8,'2026-10-06','Chưa dựng'),
(1,2,'TT-29','Content','Còn 3 ngày - chỉ đường tới 443 Phan Đình Phùng',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',16,'2026-10-07','Chưa dựng'),
(1,3,'TT-30','Content','Mai khai trương rồi - tổng hợp mọi thứ cần biết',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',2,'2026-10-09','Chưa dựng'),
(1,4,'TT-31','Content','Livestream lễ khai trương',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',4,'2026-10-10','Chưa dựng'),
(1,5,'TT-32','Content','Ngày khai trương ở 443 Phan Đình Phùng',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',8,'2026-10-10','Chưa dựng'),
(1,6,'TT-33','Content','Khách nói gì về cơ sở mới',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',16,'2026-10-12','Chưa dựng'),
(1,1,'TT-34','Content','5 topping nên gọi thêm khi ăn mì cay',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',2,'2026-10-15','Chưa dựng'),
(1,2,'TT-35','Content','Dưới 100k ăn được gì ở Kitachi',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',4,'2026-10-19','Chưa dựng'),
(1,3,'TT-36','Content','Đi 4 người ăn mì cay hết bao nhiêu?',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',8,'2026-10-24','Chưa dựng'),
(1,4,'FB-01','Content','Teaser cơ sở 2',NULL,'Trang Linh',NULL,'Công Tuân','Cao',16,'2026-09-27','Lên ý tưởng'),
(1,5,'FB-02','Content','Công bố cơ sở 2 tại 443 Phan Đình Phùng',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',2,'2026-09-28','Lên ý tưởng'),
(1,6,'FB-03','Content','Giải thích khác biệt giữa 2 cơ sở',NULL,'Trang Linh',NULL,'Công Tuân','Cao',4,'2026-09-29','Lên ý tưởng'),
(1,1,'FB-04','Content','Menu & bảng giá cơ sở 2',NULL,'Trang Linh',NULL,'Công Tuân','Cao',8,'2026-09-30','Lên ý tưởng'),
(1,2,'FB-05','Content','Minigame tag bạn nhận voucher',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',16,'2026-10-01','Lên ý tưởng'),
(1,3,'FB-06','Content','Công bố toàn bộ ưu đãi khai trương',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',2,'2026-10-02','Lên ý tưởng'),
(1,4,'FB-07','Content','Không gian & góc check-in',NULL,'Trang Linh',NULL,'Công Tuân','Cao',4,'2026-10-04','Lên ý tưởng'),
(1,5,'FB-08','Content','Tuyển dụng nhân sự cơ sở 2',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',8,'2026-10-05','Lên ý tưởng'),
(1,6,'FB-09','Content','Đếm ngược còn 3 ngày',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',16,'2026-10-07','Lên ý tưởng'),
(1,1,'FB-10','Content','Chỉ đường & hướng dẫn để xe',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',2,'2026-10-08','Lên ý tưởng'),
(1,2,'FB-11','Content','Ngày mai khai trương',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',4,'2026-10-09','Lên ý tưởng'),
(1,3,'FB-12','Content','Không khí ngày khai trương',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',8,'2026-10-10','Lên ý tưởng'),
(1,4,'FB-13','Content','Cảm ơn sau khai trương',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',16,'2026-10-11','Lên ý tưởng'),
(1,5,'FB-14','Content','Đăng lại bài viết của khách',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',2,'2026-10-13','Lên ý tưởng'),
(1,6,'FB-15','Content','Combo trưa cho dân văn phòng',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',4,'2026-10-16','Lên ý tưởng'),
(1,1,'FB-16','Content','Ưu đãi nhóm đông & liên hoan lớp',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',8,'2026-10-22','Lên ý tưởng'),
(1,2,'FB-17','Content','Chương trình thẻ thành viên',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',16,'2026-10-30','Lên ý tưởng'),
(1,3,'KK-01','Content','Tin nhắn chào mừng tự động',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',2,'2026-09-26','Lên ý tưởng'),
(1,4,'KK-02','Content','Tin nhắn khách CN1 khu vực phía Nam',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',4,'2026-10-03','Lên ý tưởng'),
(1,5,'KK-03','Content','Voucher lần 2 cho khách đã đến CN2',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',8,'2026-10-20','Lên ý tưởng'),
(1,6,'KK-04','Content','Mô tả gian hàng & thông tin quán',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',16,'2026-09-20','Lên ý tưởng'),
(1,1,'KK-05','Content','Tên & mô tả 15-20 món chủ lực',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',2,'2026-09-22','Lên ý tưởng'),
(1,2,'KK-06','Content','Bài đăng trên hồ sơ CN2',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',4,'2026-09-22','Lên ý tưởng'),
(1,3,'KK-07','Content','Nội dung trên standee chương trình khuyến mãi',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',8,'2026-09-18','Lên ý tưởng'),
(1,4,'KK-08','Content','Nội dung tent card để bàn',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',16,'2026-09-18','Lên ý tưởng'),
(1,5,'KK-09','Content','Nội dung bảng mời đánh giá Google',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',2,'2026-09-18','Lên ý tưởng'),
(1,6,'KK-10','Content','Nội dung POSM đặt tại cơ sở 1',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',4,'2026-09-22','Lên ý tưởng'),
(1,1,'KK-11','Content','Nội dung tờ rơi A5 2 mặt',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',8,'2026-09-20','Lên ý tưởng'),
(1,2,'KK-12','Content','Kịch bản MC ngày khai trương',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',16,'2026-10-02','Lên ý tưởng'),
(1,3,'KK-13','Content','Kịch bản nhân viên mời check-in & xin đánh giá',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',2,'2026-10-04','Lên ý tưởng'),
(1,4,'KK-14','Content','Bộ câu trả lời inbox & bình luận thường gặp',NULL,'Hồng Hạnh',NULL,'Công Tuân','Cao',4,'2026-10-04','Lên ý tưởng'),
(1,5,'KK-15','Content','Bộ 8-10 bài đăng nhóm cộng đồng',NULL,'Hồng Hạnh',NULL,'Công Tuân','Trung bình',8,'2026-09-28','Lên ý tưởng'),
(1,6,'KK-16','Content','Kịch bản phản hồi đánh giá tiêu cực',NULL,'Hồng Hạnh',NULL,'Công Tuân','Thấp',16,'2026-10-05','Lên ý tưởng'),
(1,1,'TKS-01','Thiết kế','Bảng menu treo tường',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',2,'2026-09-15','Chưa làm'),
(1,2,'TKS-02','Thiết kế','Bảng 7 cấp độ cay',NULL,'Phạm Vỹ',NULL,'Công Tuân','Trung bình',4,'2026-09-15','Chưa làm'),
(1,3,'TKS-03','Thiết kế','Menu bàn',NULL,'Phạm Vỹ',NULL,'Công Tuân','Thấp',8,'2026-09-15','Chưa làm'),
(1,4,'TKS-04','Thiết kế','Menu mang về / giao hàng',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',16,'2026-09-15','Chưa làm'),
(1,5,'TKS-05','Thiết kế','Standee chương trình khuyến mãi',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',2,'2026-09-18','Chưa làm'),
(1,6,'TKS-06','Thiết kế','Standee giới thiệu CN2 đặt tại CN1',NULL,'Phạm Vỹ',NULL,'Công Tuân','Thấp',4,'2026-09-22','Chưa làm'),
(1,1,'TKS-07','Thiết kế','Tent card để bàn',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',8,'2026-09-18','Chưa làm'),
(1,2,'TKS-08','Thiết kế','Wobbler / kệ mica quầy',NULL,'Phạm Vỹ',NULL,'Công Tuân','Trung bình',16,'2026-09-18','Chưa làm'),
(1,3,'TKS-09','Thiết kế','Bảng QR đánh giá Google',NULL,'Phạm Vỹ',NULL,'Công Tuân','Thấp',2,'2026-09-20','Chưa làm'),
(1,4,'TKS-10','Thiết kế','Backdrop check-in',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',4,'2026-09-22','Chưa làm'),
(1,5,'TKS-11','Thiết kế','Khung ảnh check-in cầm tay',NULL,'Phạm Vỹ',NULL,'Công Tuân','Trung bình',8,'2026-09-22','Chưa làm'),
(1,6,'TKS-12','Thiết kế','Decal kính mặt tiền',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',16,'2026-09-20','Chưa làm'),
(1,1,'TKS-13','Thiết kế','Decal sàn chỉ dẫn',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',2,'2026-09-20','Chưa làm'),
(1,2,'TKS-14','Thiết kế','Biển hướng dẫn để xe',NULL,'Phạm Vỹ',NULL,'Công Tuân','Trung bình',4,'2026-10-02','Chưa làm'),
(1,3,'TKS-15','Thiết kế','Bảng thông tin phân biệt 2 cơ sở',NULL,'Phạm Vỹ',NULL,'Công Tuân','Thấp',8,'2026-10-02','Chưa làm'),
(1,4,'TKS-16','Thiết kế','Phông sân khấu khai trương',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',16,'2026-10-02','Chưa làm'),
(1,5,'TKS-17','Thiết kế','Banner mặt tiền',NULL,'Phạm Vỹ',NULL,'Công Tuân','Trung bình',2,'2026-09-28','Chưa làm'),
(1,6,'TKS-18','Thiết kế','Băng rôn tuyến đường',NULL,'Phạm Vỹ',NULL,'Công Tuân','Thấp',4,'2026-09-28','Chưa làm'),
(1,1,'TKS-19','Thiết kế','Sticker dán ly / hộp / túi mang về',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',8,'2026-09-20','Chưa làm'),
(1,2,'TKS-20','Thiết kế','Túi giấy / hộp mang về',NULL,'Phạm Vỹ',NULL,'Công Tuân','Trung bình',16,'2026-09-20','Chưa làm'),
(1,3,'TKS-21','Thiết kế','Tờ rơi A5 hai mặt',NULL,'Phạm Vỹ',NULL,'Công Tuân','Thấp',2,'2026-09-20','Chưa làm'),
(1,4,'TKS-22','Thiết kế','Voucher khai trương',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',4,'2026-09-20','Chưa làm'),
(1,5,'TKS-23','Thiết kế','Thẻ thành viên',NULL,'Phạm Vỹ',NULL,'Công Tuân','Trung bình',8,'2026-09-22','Chưa làm'),
(1,6,'TKS-24','Thiết kế','Đồng phục & name tag (artwork)',NULL,'Phạm Vỹ',NULL,'Công Tuân','Thấp',16,'2026-09-14','Chưa làm'),
(1,1,'TKS-25','Thiết kế','Số bàn (bảng số để bàn)',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',2,'2026-09-18','Chưa làm'),
(1,2,'TKS-26','Thiết kế','Mẫu hoá đơn POS',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',4,'2026-09-28','Chưa làm'),
(1,3,'TKS-27','Thiết kế','Thẻ dán / sticker bộ nhận diện',NULL,'Phạm Vỹ',NULL,'Công Tuân','Thấp',8,'2026-09-20','Chưa làm'),
(1,4,'TKS-28','Thiết kế','Bảng số thứ tự / thẻ chờ',NULL,'Phạm Vỹ',NULL,'Công Tuân','Cao',16,'2026-10-02','Chưa làm'),
(1,5,'TKS-29','Thiết kế','Bảng tóm tắt CTKM dán quầy',NULL,'Phạm Vỹ',NULL,'Công Tuân','Trung bình',2,'2026-10-04','Chưa làm'),
(1,6,'TKD-01','Thiết kế','Ảnh bìa fanpage (cập nhật 2 cơ sở)',NULL,'Diệu Thảo',NULL,'Công Tuân','Thấp',4,'2026-09-26','Chưa làm'),
(1,1,'TKD-02','Thiết kế','Bộ ảnh teaser',NULL,'Diệu Thảo',NULL,'Công Tuân','Cao',8,'2026-09-26','Chưa làm'),
(1,2,'TKD-03','Thiết kế','Ảnh công bố cơ sở 2',NULL,'Diệu Thảo',NULL,'Công Tuân','Trung bình',16,'2026-09-27','Chưa làm'),
(1,3,'TKD-04','Thiết kế','Ảnh so sánh 2 cơ sở',NULL,'Diệu Thảo',NULL,'Công Tuân','Cao',2,'2026-09-28','Chưa làm'),
(1,4,'TKD-05','Thiết kế','Poster ưu đãi khai trương (bản feed)',NULL,'Diệu Thảo',NULL,'Công Tuân','Cao',4,'2026-09-30','Chưa làm'),
(1,5,'TKD-06','Thiết kế','Poster ưu đãi (bản story)',NULL,'Diệu Thảo',NULL,'Công Tuân','Trung bình',8,'2026-09-30','Chưa làm'),
(1,6,'TKD-07','Thiết kế','Ảnh minigame',NULL,'Diệu Thảo',NULL,'Công Tuân','Thấp',16,'2026-09-29','Chưa làm'),
(1,1,'TKD-08','Thiết kế','Bộ 3 ảnh đếm ngược (3-2-1)',NULL,'Diệu Thảo',NULL,'Công Tuân','Cao',2,'2026-10-04','Chưa làm'),
(1,2,'TKD-09','Thiết kế','Ảnh bản đồ chỉ đường',NULL,'Diệu Thảo',NULL,'Công Tuân','Trung bình',4,'2026-10-05','Chưa làm'),
(1,3,'TKD-10','Thiết kế','Poster tổng hợp ngày khai trương',NULL,'Diệu Thảo',NULL,'Công Tuân','Thấp',8,'2026-10-06','Chưa làm'),
(1,4,'TKD-11','Thiết kế','Motion graphic địa chỉ 443',NULL,'Diệu Thảo',NULL,'Công Tuân','Cao',16,'2026-09-27','Chưa làm'),
(1,5,'TKD-12','Thiết kế','Đồ hoạ thang 7 cấp độ cay',NULL,'Diệu Thảo',NULL,'Công Tuân','Trung bình',2,'2026-09-28','Chưa làm'),
(1,6,'TKD-13','Thiết kế','Khung overlay livestream',NULL,'Diệu Thảo',NULL,'Công Tuân','Thấp',4,'2026-10-07','Chưa làm'),
(1,1,'TKD-14','Thiết kế','Bộ 4 slide thông tin khai trương',NULL,'Diệu Thảo',NULL,'Công Tuân','Cao',8,'2026-10-06','Chưa làm'),
(1,2,'TKD-15','Thiết kế','Ảnh bìa gian hàng app giao hàng',NULL,'Diệu Thảo',NULL,'Công Tuân','Trung bình',16,'2026-09-22','Chưa làm'),
(1,3,'TKD-16','Thiết kế','Bộ 15-20 ảnh món cho app giao hàng',NULL,'Diệu Thảo',NULL,'Công Tuân','Thấp',2,'2026-09-22','Chưa làm'),
(1,4,'TKD-17','Thiết kế','Banner ZNS',NULL,'Diệu Thảo',NULL,'Công Tuân','Cao',4,'2026-10-01','Chưa làm'),
(1,5,'TKD-18','Thiết kế','Ảnh bìa Zalo OA',NULL,'Diệu Thảo',NULL,'Công Tuân','Cao',8,'2026-09-26','Chưa làm'),
(1,6,'TKD-19','Thiết kế','Ảnh kèm bài đăng Google Business',NULL,'Diệu Thảo',NULL,'Công Tuân','Thấp',16,'2026-09-22','Chưa làm'),
(1,1,'TKD-20','Thiết kế','Khung viền đồng bộ đăng lại UGC',NULL,'Diệu Thảo',NULL,'Công Tuân','Cao',2,'2026-10-11','Chưa làm'),
(1,2,'TKD-21','Thiết kế','Poster combo trưa',NULL,'Diệu Thảo',NULL,'Công Tuân','Trung bình',4,'2026-10-14','Chưa làm'),
(1,3,'TKD-22','Thiết kế','Poster ưu đãi nhóm đông',NULL,'Diệu Thảo',NULL,'Công Tuân','Thấp',8,'2026-10-20','Chưa làm'),
(1,4,'TKD-23','Thiết kế','Ảnh giới thiệu thẻ thành viên',NULL,'Diệu Thảo',NULL,'Công Tuân','Cao',16,'2026-10-28','Chưa làm'),
(1,5,'KOC-01','Booking KOC/KOL','KOC nano địa phương · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',2,'2026-10-02','Chưa liên hệ'),
(1,6,'KOC-02','Booking KOC/KOL','KOC nano địa phương · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',4,'2026-10-03','Chưa liên hệ'),
(1,1,'KOC-03','Booking KOC/KOL','KOC nano địa phương · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',8,'2026-10-04','Chưa liên hệ'),
(1,2,'KOC-04','Booking KOC/KOL','KOC nano địa phương · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',16,'2026-10-05','Chưa liên hệ'),
(1,3,'KOC-05','Booking KOC/KOL','KOC nano địa phương · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',2,'2026-10-07','Chưa liên hệ'),
(1,4,'KOC-06','Booking KOC/KOL','KOC nano địa phương · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',4,'2026-10-12','Chưa liên hệ'),
(1,5,'KOC-07','Booking KOC/KOL','KOC micro · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',8,'2026-10-04','Chưa liên hệ'),
(1,6,'KOC-08','Booking KOC/KOL','KOC micro · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',16,'2026-10-06','Chưa liên hệ'),
(1,1,'KOC-09','Booking KOC/KOL','KOC micro · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',2,'2026-10-08','Chưa liên hệ'),
(1,2,'KOC-10','Booking KOC/KOL','KOC micro · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',4,'2026-10-13','Chưa liên hệ'),
(1,3,'KOC-11','Booking KOC/KOL','KOL tầm trung · chưa chốt tên',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',8,'2026-10-07','Chưa liên hệ'),
(1,4,'KOC-12','Booking KOC/KOL','KOL tầm trung · chưa chốt tên',NULL,'Công Tuân',NULL,'Công Tuân','Cao',16,'2026-10-10','Chưa liên hệ'),
(1,5,'KOC-13','Booking KOC/KOL','Fanpage & group cộng đồng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',2,'2026-09-30','Chưa liên hệ'),
(1,6,'KOC-14','Booking KOC/KOL','Fanpage & group cộng đồng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',4,'2026-10-05','Chưa liên hệ'),
(1,1,'KOC-15','Booking KOC/KOL','Fanpage & group cộng đồng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',8,'2026-10-14','Chưa liên hệ'),
(1,2,'KOC-16','Booking KOC/KOL','Barter đổi suất ăn · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',16,'2026-10-10','Chưa liên hệ'),
(1,3,'KOC-17','Booking KOC/KOL','Barter đổi suất ăn · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',2,'2026-10-11','Chưa liên hệ'),
(1,4,'KOC-18','Booking KOC/KOL','Barter đổi suất ăn · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',4,'2026-10-12','Chưa liên hệ'),
(1,5,'KOC-19','Booking KOC/KOL','Barter đổi suất ăn · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',8,'2026-10-13','Chưa liên hệ'),
(1,6,'KOC-20','Booking KOC/KOL','Barter đổi suất ăn · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',16,'2026-10-14','Chưa liên hệ'),
(1,1,'KOC-21','Booking KOC/KOL','Barter đổi suất ăn · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',2,'2026-10-15','Chưa liên hệ'),
(1,2,'KOC-22','Booking KOC/KOL','Barter đổi suất ăn · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',4,'2026-10-16','Chưa liên hệ'),
(1,3,'KOC-23','Booking KOC/KOL','Barter đổi suất ăn · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',8,'2026-10-17','Chưa liên hệ'),
(1,4,'KOC-24','Booking KOC/KOL','UGC khách hàng có thưởng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',16,'2026-10-10','Chưa liên hệ'),
(1,5,'KOC-25','Booking KOC/KOL','UGC khách hàng có thưởng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',2,'2026-10-11','Chưa liên hệ'),
(1,6,'KOC-26','Booking KOC/KOL','UGC khách hàng có thưởng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',4,'2026-10-12','Chưa liên hệ'),
(1,1,'KOC-27','Booking KOC/KOL','UGC khách hàng có thưởng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',8,'2026-10-13','Chưa liên hệ'),
(1,2,'KOC-28','Booking KOC/KOL','UGC khách hàng có thưởng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',16,'2026-10-14','Chưa liên hệ'),
(1,3,'KOC-29','Booking KOC/KOL','UGC khách hàng có thưởng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',2,'2026-10-15','Chưa liên hệ'),
(1,4,'KOC-30','Booking KOC/KOL','UGC khách hàng có thưởng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',4,'2026-10-16','Chưa liên hệ'),
(1,5,'KOC-31','Booking KOC/KOL','UGC khách hàng có thưởng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Trung bình',8,'2026-10-17','Chưa liên hệ'),
(1,6,'KOC-32','Booking KOC/KOL','UGC khách hàng có thưởng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Thấp',16,'2026-10-18','Chưa liên hệ'),
(1,1,'KOC-33','Booking KOC/KOL','UGC khách hàng có thưởng · chưa chốt tên',NULL,'Trang Linh',NULL,'Công Tuân','Cao',2,'2026-10-19','Chưa liên hệ'),
(1,2,'KOC-34','Booking KOC/KOL','Livestream cùng KOC · chưa chốt tên',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',4,'2026-10-10','Chưa liên hệ'),
(1,3,'CD-01','Chiến dịch','CD1 - Teaser & Gây tò mò',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',8,NULL,'Chưa chạy'),
(1,4,'CD-02','Chiến dịch','CD2 - Công bố & Giải thích khác biệt',NULL,'Công Tuân',NULL,'Công Tuân','Cao',16,NULL,'Chưa chạy'),
(1,5,'CD-03','Chiến dịch','CD3 - Ưu đãi & Thu data',NULL,'Công Tuân',NULL,'Công Tuân','Cao',2,NULL,'Chưa chạy'),
(1,6,'CD-04','Chiến dịch','CD4 - Nhắc lịch cao điểm',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',4,NULL,'Chưa chạy'),
(1,1,'CD-05','Chiến dịch','CD5 - Ngày khai trương',NULL,'Công Tuân',NULL,'Công Tuân','Cao',8,NULL,'Chưa chạy'),
(1,2,'CD-06','Chiến dịch','CD6 - Chuyển đổi & Giữ nhiệt',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',16,NULL,'Chưa chạy'),
(1,3,'CD-07','Chiến dịch','CD7 - Khách quay lại & Trung thành',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',2,NULL,'Chưa chạy'),
(1,4,'APP-01','App bán hàng','Chuẩn bị hồ sơ & đăng ký gian hàng cơ sở 2',NULL,'Công Tuân',NULL,'Công Tuân','Cao',4,'2026-09-15','Chưa làm'),
(1,5,'APP-02','App bán hàng','Khai toạ độ chính xác & kiểm tra hiển thị',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',8,'2026-09-22','Chưa làm'),
(1,6,'APP-03','App bán hàng','Chia lại bán kính giao hàng của CẢ HAI cơ sở',NULL,'Công Tuân',NULL,'Công Tuân','Cao',16,'2026-09-26','Chưa làm'),
(1,1,'APP-04','App bán hàng','Đặt tên gian hàng & mô tả có từ khoá','Phối hợp cùng: Trang Linh','Công Tuân',NULL,'Công Tuân','Cao',2,'2026-09-22','Chưa làm'),
(1,2,'APP-05','App bán hàng','Dựng menu, đặt tên món và mô tả','Phối hợp cùng: Trang Linh','Công Tuân',NULL,'Công Tuân','Trung bình',4,'2026-09-24','Chưa làm'),
(1,3,'APP-06','App bán hàng','Ảnh món chuẩn kích thước từng app',NULL,'Phạm Vỹ',NULL,'Công Tuân','Thấp',8,'2026-09-24','Chưa làm'),
(1,4,'APP-07','App bán hàng','Đăng ký nhãn Quán mới & chương trình của sàn',NULL,'Công Tuân',NULL,'Công Tuân','Cao',16,'2026-09-28','Chưa làm'),
(1,5,'APP-08','App bán hàng','Mua gói quảng cáo nội sàn',NULL,'Công Tuân',NULL,'Công Tuân','Trung bình',2,'2026-10-07','Chưa làm'),
(1,6,'APP-09','App bán hàng','Chạy flash sale khung giờ thấp điểm',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',4,'2026-10-13','Chưa làm'),
(1,1,'APP-10','App bán hàng','Chạy đơn test trước khai trương','Phối hợp cùng: Vận hành','Công Tuân',NULL,'Công Tuân','Cao',8,'2026-10-07','Chưa làm'),
(1,2,'APP-11','App bán hàng','Chuẩn hoá thời gian chuẩn bị món','Phối hợp cùng: Vận hành','Công Tuân',NULL,'Công Tuân','Trung bình',16,'2026-10-07','Chưa làm'),
(1,3,'APP-12','App bán hàng','Kiểm soát tỉ lệ huỷ đơn & khoá món hết hàng','Phối hợp cùng: Vận hành','Công Tuân',NULL,'Công Tuân','Thấp',2,'2026-10-10','Chưa làm'),
(1,4,'APP-13','App bán hàng','Kèm tờ rơi & sticker trong mỗi đơn giao','Phối hợp cùng: Vận hành','Công Tuân',NULL,'Công Tuân','Cao',4,'2026-10-10','Chưa làm'),
(1,5,'APP-14','App bán hàng','Phản hồi 100% đánh giá trên app trong 24h','Phối hợp cùng: Trang Linh','Công Tuân',NULL,'Công Tuân','Trung bình',8,'2026-10-11','Chưa làm'),
(1,6,'APP-15','App bán hàng','Theo dõi thứ hạng từ khoá hằng tuần',NULL,'Công Tuân',NULL,'Công Tuân','Thấp',16,'2026-10-17','Chưa làm'),
(1,1,'APP-16','App bán hàng','Báo cáo hiệu quả kênh app hằng tuần','Phối hợp cùng: Kế toán','Công Tuân',NULL,'Công Tuân','Cao',2,'2026-10-17','Chưa làm'),
(1,2,'GV-01','Giao việc nội bộ','Viết lại caption bài công bố cơ sở 2',NULL,'Trang Linh',NULL,'Công Tuân','Cao',4,'2026-08-14','Mới giao'),
(1,3,'GV-02','Giao việc nội bộ','Sửa poster ưu đãi — sai giá combo',NULL,'Phạm Vỹ',NULL,'Công Tuân','Thấp',8,'2026-08-13','Đang làm'),
(1,4,'GV-03','Giao việc nội bộ','Dựng lại motion địa chỉ 443 cho bản dọc',NULL,'Diệu Thảo',NULL,'Công Tuân','Cao',16,'2026-08-16','Chờ duyệt'),
(2,2,'ND-01','Kế hoạch chung','Lên lịch nội dung tuần cho 10 kênh',NULL,'Trang Linh','Công Tuân','Công Tuân','Trung bình',4,'2026-08-14','Chưa bắt đầu'),
(2,3,'ND-02','Content','Dựng kho 10 video dự phòng cho TikTok',NULL,'Hồng Hạnh','Công Tuân','Công Tuân','Trung bình',4,'2026-08-16','Chưa bắt đầu'),
(2,4,'ND-03','Thiết kế','Chuẩn hoá bộ khung thiết kế bài Facebook',NULL,'Diệu Thảo','Công Tuân','Công Tuân','Trung bình',4,'2026-08-18','Chưa bắt đầu'),
(2,3,'ND-04','Thiết kế','Hậu kỳ bộ ảnh món mới',NULL,'Diệu Thảo','Công Tuân','Công Tuân','Trung bình',4,'2026-08-20','Chưa bắt đầu'),
(2,5,'ND-05','Kế hoạch chung','Báo cáo hiệu quả kênh tháng 8',NULL,'Công Tuân','Công Tuân','Công Tuân','Trung bình',4,'2026-08-22','Chưa bắt đầu'),
(3,6,'TET-01','Kế hoạch chung','Chốt concept & thông điệp chiến dịch Tết',NULL,'Công Tuân','Công Tuân','Công Tuân','Cao',8,'2026-11-12','Chưa bắt đầu'),
(3,6,'TET-02','Kế hoạch chung','Nghiên cứu nội dung Tết của đối thủ năm ngoái',NULL,'Trang Linh','Công Tuân','Công Tuân','Trung bình',16,'2026-11-15','Chưa bắt đầu'),
(3,6,'TET-03','Thiết kế','Lên moodboard & bộ nhận diện Tết',NULL,'Phạm Vỹ','Công Tuân','Công Tuân','Cao',4,'2026-11-19','Chưa bắt đầu'),
(3,6,'TET-04','Content','Xây dựng kho ý tưởng 30 video Tết',NULL,'Hồng Hạnh','Công Tuân','Công Tuân','Cao',8,'2026-11-22','Chưa bắt đầu'),
(3,6,'TET-05','Kế hoạch chung','Chốt combo & mức giá dịp Tết',NULL,'Công Tuân','Công Tuân','Công Tuân','Cao',16,'2026-11-24','Chưa bắt đầu'),
(3,6,'TET-06','Thiết kế','Dựng TVC Tết bản 30 giây',NULL,'Diệu Thảo','Công Tuân','Công Tuân','Cao',4,'2026-12-02','Chưa bắt đầu'),
(3,6,'TET-07','Thiết kế','Thiết kế bộ POSM Tết cho hai cơ sở',NULL,'Phạm Vỹ','Công Tuân','Công Tuân','Trung bình',8,'2026-12-06','Chưa bắt đầu'),
(3,6,'TET-08','Booking KOC/KOL','Lên kế hoạch booking KOC dịp Tết',NULL,'Trang Linh','Công Tuân','Công Tuân','Trung bình',16,'2026-12-08','Chưa bắt đầu'),
(3,6,'TET-09','Chiến dịch','Đặt lịch chạy quảng cáo Tết sớm để giữ giá',NULL,'Công Tuân','Công Tuân','Công Tuân','Cao',4,'2026-12-12','Chưa bắt đầu'),
(3,6,'TET-10','Content','Chuẩn bị nội dung lì xì & minigame',NULL,'Hồng Hạnh','Công Tuân','Công Tuân','Thấp',8,'2026-12-17','Chưa bắt đầu');

insert into posts (title, writer, editor, status, ctype, channel_id, channel, platform, stream, fmt, goal, project_id, design_due, design_started, design_done, pub_date, pub_time, brief, brief_link, brief_img, script, link_footage, asset, handoff_by, handoff_at, hashtag, note, views, eng, shares, saves, hook, caption, cta, sound, duration, props, seo_title, seo_desc, keyword, slug, thumb, audience, geotag, offer_end, img_count, send_count, ad_budget) values
('Review khách hàng dùng combo mì cay tháng 7','Trang Linh','Phạm Vỹ','Đã đăng','Review khách hàng',1,'@micaykitachi','TikTok','tiktok','Video ngắn','Lượt tương tác',2,'2026-07-14',NULL,'2026-07-15','2026-07-18','19:30','Cắt 5 feedback khách nổi bật, mỗi feedback 6 giây, sub chữ vàng, nhạc trend nhẹ.','docs.google.com/…/brief-review-t7',NULL,'Tổng hợp 5 feedback khách hàng nổi bật trong tháng, kèm ảnh thực tế.','drive.google.com/…/footage-review-t7','drive.google.com/…/review-t7-final','Trang Linh',NULL,'#micaykitachi #review',NULL,12400,860,45,120,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hậu trường: một buổi nhập nguyên liệu ở bếp trung tâm','Hồng Hạnh','Diệu Thảo','Đã đăng','Kịch bản TikTok',2,'@chuyenmicaykitachi','TikTok','tiktok','Video ngắn','Lượt xem',2,'2026-07-16',NULL,'2026-07-17','2026-07-20','20:00','Tông tài liệu, không nhạc trend. Thumbnail chữ lớn + dấu ? vàng, gắn tag SERIES.','docs.google.com/…/brief-hautruong-02',NULL,'Quay quy trình nhập hàng từ 5h sáng, giọng kể chậm.','drive.google.com/…/footage-bep','drive.google.com/…/hautruong-02-final','Hồng Hạnh',NULL,'#chuyenmicay #series','Thảo dựng lần 1 nhịp hơi nhanh, đã sửa lại.',45200,3100,210,640,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Review quán bò nướng góc phố – POV người địa phương','Hồng Hạnh','Diệu Thảo','Đã đăng','Review khách hàng',4,'@anuongquangngai','TikTok','tiktok','Video ngắn','Lượt xem',2,'2026-07-18',NULL,'2026-07-19','2026-07-22','19:00','Giữ giọng địa phương, tiêu đề nổi bật 3 dòng đầu, cận cảnh món trong 2 giây đầu.','docs.google.com/…/brief-review-bo',NULL,'POV đi ăn tối, chấm điểm 3 tiêu chí.','drive.google.com/…/footage-bonuong','drive.google.com/…/review-bo-final','Hồng Hạnh',NULL,'#anuongquangngai',NULL,68400,5200,390,1100,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bài SEO: chọn món cho người mới tới quán','Trang Linh','Không cần','Đã đăng','Bài SEO website',8,'Website hệ thống','Website','social','Bài viết','Website visit',2,NULL,NULL,NULL,'2026-07-22','09:00',NULL,NULL,NULL,'Bài chuẩn SEO 1200 từ, 3 heading chính.',NULL,'docs.google.com/…/seo-chon-mon',NULL,NULL,NULL,NULL,2300,90,12,35,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Cập nhật ảnh không gian quán lên Google Maps','Trang Linh','Phạm Vỹ','Đã đăng','Nội dung Google Maps',9,'Google Maps – cơ sở 1','Google Maps','social','Album ảnh','Lượt gọi / chỉ đường',2,'2026-07-20',NULL,'2026-07-21','2026-07-24','10:00','8 ảnh: mặt tiền, quầy, 3 món signature, không gian tầng 2. Chỉnh sáng ấm.','docs.google.com/…/brief-maps-t7',NULL,'Bộ ảnh sau khi sửa lại quầy.','drive.google.com/…/anh-goc-quan','drive.google.com/…/maps-t7-final','Trang Linh',NULL,NULL,NULL,1800,40,5,18,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Khuyến mãi mừng sinh nhật hệ thống','Hồng Hạnh','Phạm Vỹ','Huỷ bỏ','Khuyến mãi',1,'@micaykitachi','TikTok','tiktok','Ảnh đơn','Đơn hàng',2,'2026-07-23',NULL,NULL,'2026-07-25','08:00','Key visual sinh nhật, tông đỏ – vàng.',NULL,NULL,'Dời sang tháng 8, huỷ bài này.',NULL,NULL,'Hồng Hạnh',NULL,NULL,'Dời sang campaign tháng 8.',0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Video dài: quy trình phục vụ tại cửa hàng','Trang Linh','Phạm Vỹ','Đã lên lịch','Giới thiệu sản phẩm',10,'YouTube hệ thống','YouTube','social','Video dài','Lượt xem',2,'2026-08-11',NULL,'2026-07-25','2026-08-15','18:00','Video 6 phút, 4 chương, có intro 10 giây và outro CTA đặt bàn.','docs.google.com/…/brief-quytrinh',NULL,'Quay toàn bộ quy trình từ lúc khách bước vào.','drive.google.com/…/footage-quytrinh','drive.google.com/…/quytrinh-final','Trang Linh',NULL,'#hethong','Đã hẹn giờ trên YouTube.',0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bò Bistro: cận cảnh sườn bò nướng tảng','Hồng Hạnh','Diệu Thảo','Đang thiết kế','Giới thiệu sản phẩm',3,'@bobistro76','TikTok','tiktok','Video ngắn','Lượt xem',2,'2026-08-10',NULL,NULL,'2026-08-12','20:00','Tông điện ảnh, ấm. Slow-motion lúc cắt miếng thịt, khói bốc. Không dùng nhạc trend ồn.','docs.google.com/…/brief-bobistro-01',NULL,'15 cảnh cận, kết bằng logo Bò Bistro.','drive.google.com/…/footage-suonbo',NULL,'Hồng Hạnh',NULL,NULL,'Thảo dựng bản 1 trước 12h, Vỹ duyệt buổi chiều.',0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bài Facebook: ưu đãi cuối tuần','Trang Linh','Phạm Vỹ','Đã phê duyệt','Khuyến mãi',6,'Fanpage Mì Cay Kitachi','Facebook','social','Ảnh đơn','Lượt tương tác',1,'2026-08-09',NULL,NULL,'2026-08-11','19:00','1 ảnh vuông 1080, giá ưu đãi nổi bật, logo góc phải dưới.','docs.google.com/…/brief-uudai-ct',NULL,'Post ưu đãi áp dụng T7–CN.',NULL,NULL,'Trang Linh',NULL,'#uudai #cuoituan','Tuân đã duyệt nội dung, chờ Vỹ ra ảnh.',0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Hướng dẫn ăn mì cay đúng cấp độ cho khách mới','Trang Linh','Diệu Thảo','Chờ duyệt thiết kế','Hướng dẫn sử dụng',7,'Instagram Mì Cay Kitachi','Instagram','social','Infographic','Lượt lưu',1,'2026-08-08',NULL,'2026-07-27','2026-08-10','11:00','Infographic 7 cấp độ cay, mỗi cấp 1 icon ớt, nền tối, chữ trắng.','docs.google.com/…/brief-capdo-cay',NULL,'Giải thích 7 cấp độ + gợi ý cho người mới.',NULL,'canva.com/…/capdo-cay-v1','Trang Linh',NULL,'#huongdan','Thảo làm xong bản 1, chờ Vỹ duyệt bố cục.',0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bắt trend nhạc tháng 8 tại quầy pha chế','Hồng Hạnh','Diệu Thảo','Chờ phê duyệt','Kịch bản TikTok',1,'@micaykitachi','TikTok','tiktok','Video ngắn','Lượt xem',2,'2026-08-07',NULL,NULL,'2026-08-09','20:00','Bám trend đang lên, quay tại quầy, 3 nhân viên tham gia.',NULL,NULL,'Kịch bản 30 giây, 5 cảnh.',NULL,NULL,'Hồng Hạnh',NULL,'#trend','Chờ Tuân duyệt kịch bản.',0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Tuyển dụng CTV phục vụ ca tối','Công Tuân','Phạm Vỹ','Chờ phê duyệt','Tuyển dụng',6,'Fanpage Mì Cay Kitachi','Facebook','social','Ảnh đơn','Lượt tương tác',2,'2026-08-11',NULL,NULL,'2026-08-13','09:00','Ảnh tuyển dụng tông sáng, ghi rõ mức lương và ca làm.',NULL,NULL,'Mô tả công việc + quyền lợi + cách ứng tuyển.',NULL,NULL,'Công Tuân',NULL,'#tuyendung',NULL,0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Series hậu trường: một ngày của bếp trưởng','Hồng Hạnh','Diệu Thảo','Đang soạn thảo','Kịch bản TikTok',2,'@chuyenmicaykitachi','TikTok','tiktok','Video ngắn','Lượt lưu',2,'2026-08-10',NULL,NULL,'2026-08-12','20:00','Giữ đúng tông tài liệu của series, thumbnail có dấu ? vàng.',NULL,NULL,'Đang viết kịch bản.',NULL,NULL,'Hồng Hạnh',NULL,NULL,NULL,0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
('Bò Bistro: lẩu bò đêm mưa – tông điện ảnh','Trang Linh','Phạm Vỹ','Lên ý tưởng','Giới thiệu sản phẩm',3,'@bobistro76','TikTok','tiktok','Video ngắn','Lượt tương tác',2,'2026-08-06',NULL,NULL,'2026-08-08','19:30',NULL,NULL,NULL,NULL,NULL,NULL,'Trang Linh',NULL,NULL,NULL,0,0,0,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

insert into risks (id, project_id, name, detail, prob, impact, status, owner, plan) values
(1,1,'Google Maps gộp hồ sơ hai cơ sở','Hai điểm cùng tên cách 670 m rất dễ bị Google gộp. Cơ sở 1 đang có 4,7 sao với 2.841 đánh giá.','Cao','Cao','Đang theo dõi','Công Tuân','Dùng hotline khác nhau, đặt tên theo số nhà, giám sát hằng tuần'),
(2,1,'Cơ sở 2 lấy khách của cơ sở 1','Khoảng cách 670 m nên tệp khách trùng nhau nhiều.','Cao','Trung bình','Đang xử lý','Công Tuân','Phân vùng theo hướng, target quảng cáo lệch Nam'),
(3,1,'Ấn phẩm in trễ hạn khai trương','Nhà in cần 7–10 ngày, hiện đã có 2 hạng mục trễ.','Trung bình','Cao','Cảnh báo','Phạm Vỹ','Chốt file trước D-15, đặt cọc giữ chỗ nhà in'),
(4,2,'Kênh TikTok hụt nhịp đăng','5 kênh TikTok cần 19 bài/tuần, hiện chưa đạt.','Trung bình','Trung bình','Đang theo dõi','Hồng Hạnh','Dựng sẵn kho nội dung dự phòng 10 video'),
(5,2,'Quá tải khâu duyệt của Leader','Mọi bài đều qua Leader duyệt hai lần.','Cao','Trung bình','Đang xử lý','Công Tuân','Uỷ quyền duyệt nội dung thường cho Trang Linh'),
(6,3,'Chi phí quảng cáo Tết tăng mạnh','CPM mùa Tết thường tăng 40–60%.','Trung bình','Cao','Mới ghi nhận','Công Tuân','Đặt ngân sách sớm, chạy từ tháng 12');

insert into docs (id, project_id, name, cat, owner, at, link) values
(1,1,'Kế hoạch marketing khai trương CS2','Kế hoạch','Công Tuân','2026-08-01',NULL),
(2,1,'Bộ nhận diện & brand guideline','Thiết kế','Phạm Vỹ','2026-08-02',NULL),
(3,1,'Brief 34 suất booking KOC/KOL','Brief','Trang Linh','2026-08-05',NULL),
(4,1,'Bản đồ phân vùng CS1 – CS2','Nghiên cứu','Công Tuân','2026-08-03',NULL),
(5,2,'Hồ sơ 10 kênh: style & tông nội dung','Hướng dẫn','Trang Linh','2026-08-01',NULL),
(6,2,'Thư viện ảnh món ăn','Tư liệu','Diệu Thảo','2026-08-04',NULL),
(7,2,'Quy trình sản xuất một bài đăng','Quy trình','Công Tuân','2026-08-01',NULL),
(8,2,'Bộ 15 câu trả lời inbox thường gặp','Hướng dẫn','Trang Linh','2026-08-06',NULL),
(9,3,'Moodboard chiến dịch Tết 2027','Thiết kế','Phạm Vỹ','2026-08-08',NULL);

insert into meetings (id, name, date, time, mins, kind, host, who, agenda) values
(1,'Họp giao ban đầu tuần','2026-08-10','09:00',60,'Định kỳ','Công Tuân','Cả phòng','Chốt lịch đăng tuần, rà việc trễ'),
(2,'Duyệt nội dung tuần','2026-08-12','14:00',45,'Duyệt','Công Tuân','Trang Linh · Hồng Hạnh','Duyệt bài chờ trong tuần'),
(3,'Review ấn phẩm khai trương','2026-08-13','15:30',60,'Duyệt','Công Tuân','Phạm Vỹ · Diệu Thảo','Xem toàn bộ POSM trước khi gửi in'),
(4,'Họp tiến độ cơ sở 2','2026-08-14','10:00',90,'Dự án','Công Tuân','Cả phòng','Rà 220 đầu việc, chốt việc trễ'),
(5,'Brainstorm nội dung Tết','2026-08-17','14:00',90,'Ý tưởng','Trang Linh','Cả phòng','Lên ý tưởng lớn cho chiến dịch Tết'),
(6,'Tổng kết tháng 8','2026-08-31','09:00',60,'Báo cáo','Công Tuân','Cả phòng','Báo cáo số liệu, rút kinh nghiệm');

insert into reports (date, author, reviewer, status, items, blocker, plan) values
('2026-08-14','Công Tuân','Công Tuân','Đã duyệt','["Họp với bếp chốt dự báo lượng khách khai trương — đã chốt", "Rà ngân sách quảng cáo tuần — CPM đang cao hơn dự kiến 18%", "Duyệt 5 nội dung chờ trong ngày — đã duyệt 4, trả lại 1"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-14','Trang Linh','Công Tuân','Đã duyệt','["Seeding 4 nhóm cộng đồng Quảng Ngãi — đã đăng", "Lên lịch nội dung tuần cho 10 kênh — xong 7/10", "Viết caption bài công bố cơ sở 2 — đã gửi duyệt", "Duyệt bản dựng video teaser của Hạnh — yêu cầu sửa phần cuối"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-14','Hồng Hạnh','Trang Linh','Yêu cầu sửa','["Lên kịch bản video 7 cấp độ cay — đang viết", "Cắt 3 clip ngắn từ tư liệu hôm qua — đã xong", "Dựng video teaser cơ sở 2 — đã gửi chị Linh nghiệm thu"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-14','Phạm Vỹ','Công Tuân','Chưa nộp','[]'::jsonb,NULL,NULL),
('2026-08-14','Diệu Thảo','Phạm Vỹ','Chưa nộp','[]'::jsonb,NULL,NULL),
('2026-08-13','Công Tuân','Công Tuân','Đã duyệt','["Duyệt 5 nội dung chờ trong ngày — đã duyệt 4, trả lại 1", "Rà ngân sách quảng cáo tuần — CPM đang cao hơn dự kiến 18%", "Họp với bếp chốt dự báo lượng khách khai trương — đã chốt"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-13','Trang Linh','Công Tuân','Đã duyệt','["Viết caption bài công bố cơ sở 2 — đã gửi duyệt", "Lên lịch nội dung tuần cho 10 kênh — xong 7/10", "Duyệt bản dựng video teaser của Hạnh — yêu cầu sửa phần cuối", "Seeding 4 nhóm cộng đồng Quảng Ngãi — đã đăng"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-13','Hồng Hạnh','Trang Linh','Đã duyệt','["Quay hậu trường setup quán — xong 12 phút tư liệu", "Lên kịch bản video 7 cấp độ cay — đang viết", "Dựng video teaser cơ sở 2 — đã gửi chị Linh nghiệm thu", "Cắt 3 clip ngắn từ tư liệu hôm qua — đã xong"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-13','Phạm Vỹ','Công Tuân','Yêu cầu sửa','["Chuẩn hoá bộ khung thiết kế bài Facebook — đang làm", "Sửa poster ưu đãi sai giá combo — đã xong"]'::jsonb,'Chờ nhà in báo giá lại','Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-13','Diệu Thảo','Phạm Vỹ','Chờ duyệt','["Dựng lại motion địa chỉ 443 bản dọc — chờ anh Vỹ duyệt", "Hậu kỳ bộ ảnh món mới — xong 18/25 ảnh", "Làm khung overlay livestream khai trương — đã xong"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-12','Công Tuân','Công Tuân','Chờ duyệt','["Rà ngân sách quảng cáo tuần — CPM đang cao hơn dự kiến 18%", "Họp với bếp chốt dự báo lượng khách khai trương — đã chốt"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-12','Trang Linh','Công Tuân','Yêu cầu sửa','["Duyệt bản dựng video teaser của Hạnh — yêu cầu sửa phần cuối", "Seeding 4 nhóm cộng đồng Quảng Ngãi — đã đăng"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-12','Hồng Hạnh','Trang Linh','Chờ duyệt','["Cắt 3 clip ngắn từ tư liệu hôm qua — đã xong", "Quay hậu trường setup quán — xong 12 phút tư liệu", "Lên kịch bản video 7 cấp độ cay — đang viết", "Dựng video teaser cơ sở 2 — đã gửi chị Linh nghiệm thu"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-12','Phạm Vỹ','Công Tuân','Chờ duyệt','["Chuẩn hoá bộ khung thiết kế bài Facebook — đang làm", "Thiết kế standee CTKM cơ sở 2 — đã gửi Leader duyệt", "Xuất file in menu bàn gửi nhà in — đã gửi", "Sửa poster ưu đãi sai giá combo — đã xong"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-12','Diệu Thảo','Phạm Vỹ','Yêu cầu sửa','["Dựng lại motion địa chỉ 443 bản dọc — chờ anh Vỹ duyệt", "Làm khung overlay livestream khai trương — đã xong", "Hậu kỳ bộ ảnh món mới — xong 18/25 ảnh"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-11','Công Tuân','Công Tuân','Chờ duyệt','["Duyệt 5 nội dung chờ trong ngày — đã duyệt 4, trả lại 1", "Họp với bếp chốt dự báo lượng khách khai trương — đã chốt", "Rà ngân sách quảng cáo tuần — CPM đang cao hơn dự kiến 18%"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-11','Trang Linh','Công Tuân','Chờ duyệt','["Lên lịch nội dung tuần cho 10 kênh — xong 7/10", "Duyệt bản dựng video teaser của Hạnh — yêu cầu sửa phần cuối"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-11','Hồng Hạnh','Trang Linh','Yêu cầu sửa','["Cắt 3 clip ngắn từ tư liệu hôm qua — đã xong", "Lên kịch bản video 7 cấp độ cay — đang viết", "Quay hậu trường setup quán — xong 12 phút tư liệu", "Dựng video teaser cơ sở 2 — đã gửi chị Linh nghiệm thu"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-11','Phạm Vỹ','Công Tuân','Yêu cầu sửa','["Thiết kế standee CTKM cơ sở 2 — đã gửi Leader duyệt", "Xuất file in menu bàn gửi nhà in — đã gửi", "Chuẩn hoá bộ khung thiết kế bài Facebook — đang làm", "Sửa poster ưu đãi sai giá combo — đã xong"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp'),
('2026-08-11','Diệu Thảo','Phạm Vỹ','Đã duyệt','["Hậu kỳ bộ ảnh món mới — xong 18/25 ảnh", "Làm khung overlay livestream khai trương — đã xong"]'::jsonb,NULL,'Hoàn tất phần còn lại và bắt đầu hạng mục kế tiếp');

insert into approvals (id, kind, title, requester, approver, status, amount, at) values
(1,'Ngân sách','Tăng ngân sách Meta Ads thêm 5 triệu','Trang Linh','Công Tuân','Chờ duyệt',5000000,'2026-08-14'),
(2,'Nội dung','Duyệt kịch bản video thử thách cấp độ 7','Hồng Hạnh','Công Tuân','Chờ duyệt',0,'2026-08-13'),
(3,'Thiết kế','Duyệt bộ POSM cơ sở 2 trước khi gửi in','Phạm Vỹ','Công Tuân','Chờ duyệt',0,'2026-08-12'),
(4,'Booking','Chốt 2 KOL tầm trung cho ngày khai trương','Trang Linh','Công Tuân','Đã duyệt',16000000,'2026-08-11'),
(5,'Nghỉ phép','Xin nghỉ 1 buổi chiều 20/08','Diệu Thảo','Phạm Vỹ','Đã duyệt',0,'2026-08-14'),
(6,'Chi phí','Thanh toán nhà in đợt 1','Phạm Vỹ','Công Tuân','Từ chối',19200000,'2026-08-13');

insert into kudos (id, giver, receiver, "text", point, at) values
(1,'Công Tuân','Hồng Hạnh','Video hậu trường lên xu hướng, cứu cả tuần nội dung của kênh chính',10,'2026-08-14'),
(2,'Trang Linh','Diệu Thảo','Hậu kỳ ảnh nhanh hơn hẹn 1 ngày, kịp bài Facebook cuối tuần',10,'2026-08-13'),
(3,'Phạm Vỹ','Trang Linh','Brief rõ ràng, không phải hỏi lại lần nào',10,'2026-08-12'),
(4,'Hồng Hạnh','Phạm Vỹ','Sửa poster giữa đêm để kịp lịch đăng sáng hôm sau',10,'2026-08-11'),
(5,'Diệu Thảo','Công Tuân','Duyệt nhanh, không để bài nào tắc quá nửa ngày',5,'2026-08-10');

insert into duty (id, date, who, task, done) values
(1,'2026-08-14','Trang Linh','Trực inbox & bình luận toàn kênh',false),
(2,'2026-08-15','Hồng Hạnh','Trực inbox & bình luận toàn kênh',false),
(3,'2026-08-17','Diệu Thảo','Trực inbox & bình luận toàn kênh',false),
(4,'2026-08-18','Công Tuân','Trực inbox & bình luận toàn kênh',false),
(5,'2026-08-19','Trang Linh','Trực inbox & bình luận toàn kênh',false),
(6,'2026-08-20','Hồng Hạnh','Trực inbox & bình luận toàn kênh',false),
(7,'2026-08-21','Phạm Vỹ','Trực inbox & bình luận toàn kênh',false),
(8,'2026-08-22','Diệu Thảo','Trực inbox & bình luận toàn kênh',false),
(9,'2026-08-24','Trang Linh','Trực inbox & bình luận toàn kênh',false),
(10,'2026-08-25','Hồng Hạnh','Trực inbox & bình luận toàn kênh',false),
(11,'2026-08-26','Phạm Vỹ','Trực inbox & bình luận toàn kênh',false),
(12,'2026-08-27','Diệu Thảo','Trực inbox & bình luận toàn kênh',false);

insert into settings (key, value) values
('opening_date','2026-10-10'),
('dept_name','Phòng Marketing — Kitachi'),
('budget_total','189596000'),
('budget_ads','33000000'),
('budget_koc','37600000'),
('sla_duyet','2'),
('sla_thietke','3'),
('load_max','14'),
('default_time','19:30');

insert into roles (id, name, kind, desk) values
(1,'Leader Team','leader','leader'),
(2,'Content Marketing (chung)','writer','social'),
(3,'Content Marketing TikTok','writer','tiktok'),
(4,'Designer','design','design'),
(5,'Editor','design','edit');

insert into perms (id, grp, grp_name, "key", name, scoped, vals) values
(1,'work','Công việc & dự án','task.view','Xem toàn bộ công việc',true,'{"Leader Team": "Toàn hệ thống", "Content Marketing (chung)": "Toàn hệ thống", "Content Marketing TikTok": "Trong nhóm", "Designer": "Trong nhóm", "Editor": "Của mình"}'::jsonb),
(2,'work','Công việc & dự án','task.create','Tạo và giao việc',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Cho phép", "Content Marketing TikTok": "Cho phép", "Designer": "Cho phép", "Editor": "Không"}'::jsonb),
(3,'work','Công việc & dự án','task.edit','Sửa việc của người khác',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Cho phép", "Content Marketing TikTok": "Không", "Designer": "Không", "Editor": "Không"}'::jsonb),
(4,'work','Công việc & dự án','task.delete','Xoá việc',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Không", "Content Marketing TikTok": "Không", "Designer": "Không", "Editor": "Không"}'::jsonb),
(5,'work','Công việc & dự án','project.manage','Tạo và sửa dự án',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Không", "Content Marketing TikTok": "Không", "Designer": "Không", "Editor": "Không"}'::jsonb),
(6,'content','Nội dung','post.create','Tạo nội dung mới',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Cho phép", "Content Marketing TikTok": "Cho phép", "Designer": "Không", "Editor": "Không"}'::jsonb),
(7,'content','Nội dung','post.approve','Phê duyệt nội dung',true,'{"Leader Team": "Toàn hệ thống", "Content Marketing (chung)": "Trong nhóm", "Content Marketing TikTok": "Không", "Designer": "Không", "Editor": "Không"}'::jsonb),
(8,'content','Nội dung','design.approve','Phê duyệt ấn phẩm thiết kế',true,'{"Leader Team": "Toàn hệ thống", "Content Marketing (chung)": "Không", "Content Marketing TikTok": "Không", "Designer": "Trong nhóm", "Editor": "Không"}'::jsonb),
(9,'content','Nội dung','post.publish','Đăng bài lên kênh',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Cho phép", "Content Marketing TikTok": "Cho phép", "Designer": "Không", "Editor": "Không"}'::jsonb),
(10,'content','Nội dung','channel.manage','Cấu hình kênh',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Cho phép", "Content Marketing TikTok": "Không", "Designer": "Không", "Editor": "Không"}'::jsonb),
(11,'report','Báo cáo','report.submit','Nộp báo cáo ngày',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Cho phép", "Content Marketing TikTok": "Cho phép", "Designer": "Cho phép", "Editor": "Cho phép"}'::jsonb),
(12,'report','Báo cáo','report.approve','Duyệt báo cáo',true,'{"Leader Team": "Toàn hệ thống", "Content Marketing (chung)": "Trong nhóm", "Content Marketing TikTok": "Không", "Designer": "Trong nhóm", "Editor": "Không"}'::jsonb),
(13,'report','Báo cáo','report.view','Xem báo cáo người khác',true,'{"Leader Team": "Toàn hệ thống", "Content Marketing (chung)": "Trong nhóm", "Content Marketing TikTok": "Của mình", "Designer": "Trong nhóm", "Editor": "Của mình"}'::jsonb),
(14,'report','Báo cáo','report.config','Cấu hình quy tắc báo cáo',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Không", "Content Marketing TikTok": "Không", "Designer": "Không", "Editor": "Không"}'::jsonb),
(15,'money','Ngân sách & quảng cáo','budget.view','Xem ngân sách',true,'{"Leader Team": "Toàn hệ thống", "Content Marketing (chung)": "Trong nhóm", "Content Marketing TikTok": "Không", "Designer": "Trong nhóm", "Editor": "Không"}'::jsonb),
(16,'money','Ngân sách & quảng cáo','budget.edit','Sửa ngân sách',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Không", "Content Marketing TikTok": "Không", "Designer": "Không", "Editor": "Không"}'::jsonb),
(17,'money','Ngân sách & quảng cáo','ads.create','Tạo chiến dịch quảng cáo',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Cho phép", "Content Marketing TikTok": "Không", "Designer": "Không", "Editor": "Không"}'::jsonb),
(18,'money','Ngân sách & quảng cáo','ads.update','Cập nhật số liệu quảng cáo',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Cho phép", "Content Marketing TikTok": "Cho phép", "Designer": "Không", "Editor": "Không"}'::jsonb),
(19,'org','Tổ chức','member.view','Xem danh sách thành viên',true,'{"Leader Team": "Toàn hệ thống", "Content Marketing (chung)": "Toàn hệ thống", "Content Marketing TikTok": "Toàn hệ thống", "Designer": "Toàn hệ thống", "Editor": "Toàn hệ thống"}'::jsonb),
(20,'org','Tổ chức','member.manage','Thêm và sửa nhân sự',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Không", "Content Marketing TikTok": "Không", "Designer": "Không", "Editor": "Không"}'::jsonb),
(21,'org','Tổ chức','role.manage','Phân quyền',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Không", "Content Marketing TikTok": "Không", "Designer": "Không", "Editor": "Không"}'::jsonb),
(22,'org','Tổ chức','kudos.give','Gửi ghi nhận đồng đội',false,'{"Leader Team": "Cho phép", "Content Marketing (chung)": "Cho phép", "Content Marketing TikTok": "Cho phép", "Designer": "Cho phép", "Editor": "Cho phép"}'::jsonb);

select setval('roles_id_seq',(select max(id) from roles));
select setval('perms_id_seq',(select max(id) from perms));

select setval('channels_id_seq',(select max(id) from channels));
select setval('projects_id_seq',(select max(id) from projects));
select setval('sprints_id_seq',(select max(id) from sprints));
select setval('budget_id_seq',(select max(id) from budget));
select setval('ads_id_seq',(select max(id) from ads));
select setval('risks_id_seq',(select max(id) from risks));
select setval('docs_id_seq',(select max(id) from docs));
select setval('meetings_id_seq',(select max(id) from meetings));
select setval('approvals_id_seq',(select max(id) from approvals));
select setval('kudos_id_seq',(select max(id) from kudos));
select setval('duty_id_seq',(select max(id) from duty));
